name: Deploy Next.js into Dokploy for staging environment

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Trigger Dokploy Deployment
        run: |
          curl -X POST "${{ secrets.DOKPLOY_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -H "X-GitHub-Event: push" \
          -d '{"ref": "refs/heads/main"}'
