## Trying something again.
name: Deploy Next.js into Dokploy for staging environment

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Trigger Dokploy Deployment
        # Uses a curl webhook to trigger deployment
        # Replace the URL below with your actual Dokploy Webhook URL
        run: |
          curl -X POST "${{ secrets.DOKPLOY_WEBHOOK_URL }}"
